screenW = Window.GetWidth();
screenH = Window.GetHeight();

image  = Image("splash.png");
imageW = image.GetWidth();
imageH = image.GetHeight();

scaleX = imageW / screenW;
scaleY = imageH / screenH;

if (scaleY < scaleX) image = image.Scale(screenW, imageH / scaleX);
else image = image.Scale(imageW / scaleY, screenH);

sprite = Sprite(image);
sprite.SetX((screenW - image.GetWidth())  / 2);
sprite.SetY((screenH - image.GetHeight()) / 2);
