Import('*')

# Local includes
env.Append(CPPPATH = ['#'])

# Build Info
info = env.BuildInfo('build_info.cpp', [])
AlwaysBuild(info)

prog1 = env.Program('webserver', ['webserver.cpp', info]);
prog2 = env.Program('secure_webserver', ['secure_webserver.cpp', info]);

Return('prog1 prog2')
