Import('*')

# Local includes
env.Append(CPPPATH = ['#'])

# Build Info
info = env.BuildInfo('build_info.cpp', [])
AlwaysBuild(info)

prog = env.Program('server', ['server.cpp', info]);

Return('prog')
