#!/bin/bash -e

export LC_ALL=C

# Update the system
apt-get update
#apt-get dist-upgrade -y

# Install packages
apt-get install -y git scons build-essential libssl-dev python3-dev libx11-dev \
  libxcursor-dev libxinerama-dev libxtst-dev libxft-dev pkg-config ninja-build \
  vim bash-completion

# libv8
if [ ! -e /opt/embedded-v8 ]; then
  cd /opt
  git clone https://github.com/CauldronDevelopmentLLC/embedded-v8
  cd embedded-v8
  python gn/build/gen.py
  ninja -C gn/out
  ./gn/out/gn gen --args='is_debug=false use_custom_libcxx=false is_clang=false v8_enable_i18n_support=false v8_monolithic=true v8_use_external_startup_data=false disable_libfuzzer=true use_aura=false use_dbus=false use_ozone=false use_sysroot=false use_udev=false use_x11=false use_gio=false use_glib=false v8_has_valgrind=true' out
  ninja -C out v8_monolith
fi
