#!/bin/bash -ex

SHARE=share
umask 0000 # Directories need to be writeable by the container


function update_repo() {
  if [ ! -e $SHARE/$1 ]; then
    if [[ "$2" == http* ]]; then
      git clone "$2" $SHARE/$1 -b $3
    else
      mkdir -p $SHARE/$1
      git -C $SHARE/$1 init
    fi
  fi

  if [[ "$2" == http* ]]; then
    git -C $SHARE/$1 fetch
  else
    git -C $SHARE/$1 fetch -t "$2" $3
  fi

  git -C $SHARE/$1 reset --hard FETCH_HEAD
}


mkdir -p $SHARE || true


# C!
if [ "$CBANG_HOME" != "" ]; then
  update_repo cbang "$CBANG_HOME" master
else
  update_repo cbang https://github.com/CauldronDevelopmentLLC/cbang master
fi

# CAMotics
if [ "$CAMOTICS_HOME" != "" ]; then
  update_repo camotics "$CAMOTICS_HOME" master
else
  update_repo camotics https://github.com/CauldronDevelopmentLLC/camotics master
fi

# bbctrl-firmware
update_repo bbctrl-firmware $PWD $(git branch --show-current)

# updiprog
if [ "$UPDIPROG_HOME" != "" ]; then
  update_repo updiprog "$UPDIPROG_HOME" master
else
  update_repo updiprog https://github.com/buildbotics/updiprog master
fi

# rpipdi
if [ "$RPIPDI_HOME" != "" ]; then
  update_repo rpipdi "$RPIPDI_HOME" master
else
  update_repo rpipdi https://github.com/buildbotics/rpipdi master
fi

# bbkbd
if [ "$BBKBD_HOME" != "" ]; then
  update_repo bbkbd "$BBKBD_HOME" master
else
  update_repo bbkbd https://github.com/buildbotics/bbkbd master
fi
