#!/bin/bash -ex

cd /mnt/host

# C!
export V8_INCLUDE=/opt/embedded-v8/include/
export V8_LIBPATH=/opt/embedded-v8/out/obj/
export V8_LIBNAME=v8_monolith
scons -C cbang disable_local="re2 libevent"

# CAMotics
export CBANG_HOME="/mnt/host/cbang"
scons -C camotics build/camotics.so with_gui=0

## bbkbd
make -C bbctrl-firmware/src/kbd
