#!/bin/bash -e

IMG="$1"
NEW="$2"
SIZE=$(( 26 * 1024 * 1024 * 1024 / 10 ))
VERSION=$(jq .version < package.json | tr -d \")
PKG=dist/bbctrl-$VERSION.tar.bz2
LOOP=/dev/loop5

if [ ! -e "$IMG" -o "$NEW" == "" ]; then
  echo "Usage: $0 <base.img> <new.img>"
  exit 1
fi

# Copy base image
cp "$IMG" "$NEW"

# Increase disk size
dd if=/dev/null of="$NEW" bs=1 count=1 seek=$SIZE

# Grow partition
growpart "$NEW" 2

# Resize filesystem
sudo losetup $LOOP "$NEW"
sudo partprobe $LOOP
sudo e2fsck -f ${LOOP}p2
sudo resize2fs ${LOOP}p2
sudo losetup -d $LOOP

# Remove old bbctrl packages
rm -f rpi-share/bbctrl-*.tar.bz2

# Copy files
cp $PKG scripts/setup.sh rpi-share

# Run setup script
sudo ./scripts/rpi-chroot.sh "$NEW" /mnt/host/setup.sh
