#!/bin/bash

(
    flock -n 9

    if [ "$1" != "" ]; then
      UPDATE="$(realpath "$1")"
    else
      UPDATE=/var/lib/bbctrl/firmware/update.tar.bz2
    fi

    if [ ! -e "$UPDATE" ]; then
      echo "Missing $UPDATE"
      exit 1
    fi

    systemctl stop bbctrl

    rm -rf /tmp/update
    mkdir /tmp/update
    cd /tmp/update

    LOG=/var/log/bbctrl.$(date +%Y%m%d-%H%M%S).install
    tar xf "$UPDATE"
    cd *
    if [ -x ./scripts/install.sh ]; then
      ./scripts/install.sh "$*" 2>&1 > $LOG
    else
      systemctl start bbctrl
    fi

    cd -
    rm -rf /tmp/update $UPDATE

) 9> /var/lock/bbctrl.update.lock
