ratpoison &

xset -dpms
xset s off
xset s noblank

while true; do
    tvservice -s 2>&1 | grep "state 0x40001" >/dev/null
    if [ $? -ne 0 ]; then
        /usr/local/bin/browser
    fi
    sleep 1
done
