import os
import re
from SCons.Script import *

Import('*')

env = env.Clone()

# Remove warnings
flags = env.subst('${CCFLAGS}')
flags = re.sub(r'-W((all)|(error))(\s|$)', '', flags)
env.Replace(CCFLAGS = flags)

# Build boost lib
src = []
for lib in ['iostreams', 'filesystem', 'system', 'regex']:
    src += Glob('libs/%s/src/*.cpp' % lib)

lib = env.Library('#/lib/cbang-boost', src)

Return('lib')
